-- Seed initial Warhammer 40k Kill Team factions
INSERT INTO factions (name) VALUES
  ('Space Marines'),
  ('Chaos Space Marines'),
  ('Astra Militarum'),
  ('Orks'),
  ('Necrons'),
  ('Tyranids'),
  ('Aeldari'),
  ('Drukhari'),
  ('T''au Empire'),
  ('Genestealer Cults'),
  ('Adeptus Mechanicus'),
  ('Death Guard'),
  ('Thousand Sons'),
  ('Grey Knights'),
  ('Harlequins'),
  ('Custodes'),
  ('Sisters of Battle'),
  ('Imperial Navy Breachers'),
  ('Kasrkin'),
  ('Legionaries'),
  ('Blooded'),
  ('Pathfinders'),
  ('Corsairs'),
  ('Kommandos'),
  ('Veteran Guardsmen'),
  ('Phobos Strike Team'),
  ('Intercession Squad'),
  ('Warpcoven'),
  ('Hunter Clade'),
  ('Wyrmblade')
ON CONFLICT (name) DO NOTHING;
